# Account name of remote user. Ansible will use this user account to ssh into
# the managed machines. The user must be able to use sudo without asking
# for password.
ansible_ssh_user: vagrant

# Kubernetes internal network for services.
# Kubernetes services will get fake IP addresses from this range.
# This range must not conflict with anything in your infrastructure. These
# addresses do not need to be routable and must just be an unused block of space.
kube_service_addresses: 10.100.0.0/16

# Flannel internal network (optional). When flannel is used, it will assign IP
# addresses from this range to individual pods.
# This network must be unused in your network infrastructure!
flannel_network: 4.0.0.0
# Prefix length of kube_overlay_ip range.
kube_overlay_prefix: 16


# Internal DNS configuration.
# Kubernetes can create and mainatain its own DNS server to resolve service names
# into appropriate IP addresses. It's highly advisable to run such DNS server,
# as it greatly simplifies configuration of your applications - you can use
# service names instead of magic environment variables.
# You still must manually configure all your containers to use this DNS server,
# Kubernetes won't do this for you (yet).

# Turn this varable to 'false' to disable whole DNS configuration.
dns_setup: false

# Internal DNS domain name.
# This domain must not be used in your network. Services will be discoverable
# under <service-name>.<namespace>.<domainname>, e.g.
# myservice.default.kube.local
dns_domain: kube.local

# IP address of the DNS server.
# Kubernetes will create a pod with several containers, serving as the DNS
# server and expose it under this IP address. The IP address must be from
# the range specified as kube_service_addresses above.
# And this is the IP address you should use as address of the DNS server
# in your containers.
dns_server: 10.100.50.1


# Amazon Web Services specific options (ignore when running outside AWS).

# When set to "true", this playbook will generate /etc/hosts on all managed
# machines with hostnames and IP addresses of all machines in inventory file.
# Use only when your DNS is not working.
kube_aws_create_etc_hosts: false

# Name of the cluster to create. It must be unique in your AWS account.
kube_aws_cluster_name: mykube
