---
- hosts: all
  sudo: yes
  roles:
          - common

- hosts: etcd
  sudo: yes
  roles:
          - etcd

- hosts: masters
  sudo: yes
  roles:
          - kubernetes
          - master

- hosts: minions
  sudo: yes
  roles:
          - kubernetes
          - flannel
          - minion
