---
- name: restart flannel
  service: name=flanneld state=restarted
  notify:
          - stop docker
          - start docker

- name: stop docker
  service: name=docker state=stopped

- name: reload daemon
  command: systemctl daemon-reload

- name: start docker
  service: name=docker state=started

- name: restart kubelet
  service: name=kubelet state=restarted
