---
- name: Determine if Fedora 20
  shell: "grep 'Fedora release 20 (Heisenbug)' /etc/fedora-release"
  register: is_f20
  failed_when: false
  changed_when: false

- name: Remove docker window manager on F20
  yum: pkg=docker state=absent
  when: is_f20.rc == 0 and not is_atomic

- name: UNinstall kubernetes from Fedora
  yum: pkg=kubernetes state=absent

