---
- include: fedora.yml
  when: is_rhel7.rc != 0

- include: rhel7.yml
  when: is_rhel7.rc == 0

- stat: path=/tmp/kubernetes.tar.gz
  register: kube_archive
- get_url: url=https://github.com/GoogleCloudPlatform/kubernetes/releases/download/v0.15.0/kubernetes.tar.gz dest=/tmp/ sha256sum=500a09889efa5f26bbf7042588ed147ae65aac74e149b2396cdf3aed7815ae5b
  when: kube_archive.stat.exists == False

- unarchive: src=/tmp/kubernetes.tar.gz dest=/tmp copy=no
- unarchive: src=/tmp/kubernetes/server/kubernetes-server-linux-amd64.tar.gz dest=/tmp copy=no
- command: mv /tmp/kubernetes/server/bin/kube-apiserver /bin
- command: mv /tmp/kubernetes/server/bin/kube-controller-manager /bin
- command: mv /tmp/kubernetes/server/bin/kubectl /bin
- command: mv /tmp/kubernetes/server/bin/kube-proxy /bin
- command: mv /tmp/kubernetes/server/bin/kube-scheduler /bin
- command: mv /tmp/kubernetes/server/bin/kubelet /bin

