---
- name: Install flannel
  yum: name=flannel state=latest
  when: not is_atomic

- name: Copy systemd service
  template: src=flannel.service.j2 dest=/usr/lib/systemd/system/flannel.service

- name: Launch Flannel
  service: name=flannel enabled=yes state=started
  notify:
          - restart kubelet

- name: Copy docker service
  template: src=docker.service.j2 dest=/usr/lib/systemd/system/docker.service
  notify:
          - stop docker
          - reload daemon
          - start docker
