---
- name: write apiserver
  template: src=kube-apiserver.service dest=/usr/lib/systemd/system/kube-apiserver.service
  notify:
          - reload daemon
          - restart apiserver
          - restart controller-manager
          - restart scheduler

- name: write controller-manager
  template: src=kube-controller-manager.service dest=/usr/lib/systemd/system/kube-controller-manager.service
  notify:
          - reload daemon
          - restart controller-manager

- name: write scheduler
  template: src=kube-scheduler.service dest=/usr/lib/systemd/system/kube-scheduler.service
  notify:
          - reload daemon
          - restart scheduler

- name: Enable apiserver
  service: name=kube-apiserver enabled=yes state=started

- name: Enable controller-manager
  service: name=kube-controller-manager enabled=yes state=started

- name: Enable scheduler
  service: name=kube-scheduler enabled=yes state=started

- include: load_nodes.yml

- include: firewalld.yml
  when: has_firewalld.rc == 0

- include: iptables.yml
  when: has_firewalld.rc != 0 and has_iptables.rc == 0

