---
- include: fedora.yml
  when: is_rhel7.rc != 0

- include: rhel7.yml
  when: is_rhel7.rc == 0

- name: write kubelet
  template: src=kubelet.service dest=/usr/lib/systemd/system/kubelet.service
  notify:
          - reload daemon
          - restart kubelet

- name: write kubeproxy
  template: src=kube-proxy.service dest=/usr/lib/systemd/system/kube-proxy.service
  notify:
          - reload daemon
          - restart proxy

- name: Enable cadvisor
  service: name=cadvisor enabled=yes state=started

- name: Enable kubelet
  service: name=kubelet enabled=yes state=started

- name: Enable proxy
  service: name=kube-proxy enabled=yes state=started

- include: firewalld.yml
  when: has_firewalld.rc == 0

- include: iptables.yml
  when: has_firewalld.rc != 0 and has_iptables.rc == 0
